from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class Evidence(BaseModel):
    """
    Canonical Evidence Object representing a structured fact retrieved from
    pipeline telemetry, business rules, or ML anomaly events.
    """
    evidence_id: str
    run_id: str
    hospital_id: str
    batch_id: str
    stage: str
    timestamp: datetime
    source: str # e.g., 'pipeline_events', 'rule_results', 'anomaly_events'
    evidence_type: str # e.g., 'metric', 'rule_violation', 'statistical_anomaly'
    identifier: str # rule/anomaly/metric identifier
    
    observed_value: Any
    baseline_value: Optional[Any] = None
    deviation: Optional[float] = None
    severity: str = "INFO" # INFO, WARNING, ERROR, CRITICAL
    
    source_reference: Dict[str, Any] = Field(default_factory=dict)
    
class EvidencePack(BaseModel):
    """
    The bounded collection of evidence passed to the LLM.
    """
    query: str
    intent: str
    evidence: List[Evidence] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class Fact(BaseModel):
    description: str
    evidence_ids: List[str]

class ConfirmedFinding(BaseModel):
    description: str
    evidence_ids: List[str]

class CorrelatedFinding(BaseModel):
    description: str
    evidence_ids: List[str]

class LikelyCause(BaseModel):
    cause: str
    supporting_evidence_ids: List[str]

class RCAResponse(BaseModel):
    """
    Strict contract for the final Root Cause Analysis output generated by the LLM.
    """
    incident_id: str
    run_id: str
    hospital_id: str
    batch_id: str
    affected_stage: str
    anomaly_types: List[str]
    severity: str
    status: str
    summary: str
    what_happened: str
    evidence: List[Dict[str, Any]]
    facts: List[Fact] = Field(default_factory=list)
    confirmed_findings: List[ConfirmedFinding] = Field(default_factory=list)
    correlated_findings: List[CorrelatedFinding] = Field(default_factory=list)
    likely_causes: List[LikelyCause]
    confidence: str # HIGH, MEDIUM, LOW, ZERO
    recommended_investigation: str
    sla_status: str
    source_references: List[str]
    created_at: str
    
    # Backward compatibility properties
    @property
    def affected_hospital(self) -> str:
        return self.hospital_id
        
    @property
    def affected_batch(self) -> str:
        return self.batch_id
