from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class Evidence(BaseModel):
    """
    Canonical Evidence Object representing a structured fact retrieved from
    pipeline telemetry, business rules, or ML anomaly events.
    """
    evidence_id: str
    run_id: str
    hospital_id: str
    batch_id: str
    stage: str
    timestamp: datetime
    source: str # e.g., 'pipeline_events', 'rule_results', 'anomaly_events'
    evidence_type: str # e.g., 'metric', 'rule_violation', 'statistical_anomaly'
    identifier: str # rule/anomaly/metric identifier
    
    observed_value: Any
    baseline_value: Optional[Any] = None
    deviation: Optional[float] = None
    severity: str = "INFO" # INFO, WARNING, ERROR, CRITICAL
    
    source_reference: Dict[str, Any] = Field(default_factory=dict)
    
class EvidencePack(BaseModel):
    """
    The bounded collection of evidence passed to the LLM.
    """
    query: str
    intent: str
    evidence: List[Evidence] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class LikelyCause(BaseModel):
    cause: str
    supporting_evidence_ids: List[str]

class RCAResponse(BaseModel):
    """
    Strict contract for the final Root Cause Analysis output generated by the LLM.
    """
    incident_id: str
    summary: str
    severity: str
    affected_hospital: str
    affected_batch: str
    affected_stage: str
    what_happened: str
    evidence: List[Dict[str, Any]]
    likely_causes: List[LikelyCause]
    confidence: str # HIGH, MEDIUM, LOW
    recommended_investigation: str
    source_references: List[str]
